
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjybaatgyigpqyywlmnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqeWJhYXRneWlncHF5eXdsbW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDAwNzYsImV4cCI6MjA2MDMxNjA3Nn0.3Vj8W28J_m4Xy5nbyR9TxrP6YjlXewdj7wj1OTn6dr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
